name: Deploy to Supabase

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Deploy client to Supabase
        working-directory: ./client
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # Deploya frontend till Supabase Storage eller Functions (justera efter behov)
          npx supabase storage upload --bucket your-bucket-name ./client/dist

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Build server
        working-directory: ./server
        run: npm run build

      - name: Deploy backend to Supabase
        working-directory: ./server
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # Deploya backend som Supabase Functions
          npx supabase functions deploy
